apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "charts.helm.k8s.io/v1alpha1",
          "kind": "InfiniboxCsiDriver",
          "metadata": {
            "name": "infinibox-csi-driver"
          },
          "spec": {
            "Infinibox_Cred": {
              "SecretName": "infinibox-creds",
              "hostname": "172.17.35.61",
              "inbound_secret": "0.000us07boftjo",
              "inbound_user": "iqn.2020-06.com.csi-driver-iscsi.infinidat:commonin",
              "outbound_secret": "0.00268rzvmp0r7",
              "outbound_user": "iqn.2020-06.com.csi-driver-iscsi.infinidat:commonout",
              "password": "123456",
              "username": "admin"
            },
            "csiDriverName": "infinibox-csi-driver",
            "csiDriverVersion": "1.1.0",
            "images": {
              "attachersidecar": "quay.io/k8scsi/csi-attacher:v2.0.0",
              "csidriver": "registry.connect.redhat.com/infinidat/infinibox-csidriver-certified",
              "provisionersidecar": "quay.io/k8scsi/csi-provisioner:v1.4.0",
              "registrarsidecar": "quay.io/k8scsi/csi-node-driver-registrar:v1.3.0",
              "resizersidecar": "quay.io/k8scsi/csi-resizer:v0.3.0",
              "snapshottersidecar": "quay.io/k8scsi/csi-snapshotter:v1.2.2"
            },
            "instanceCount": 1,
            "logLevel": "info",
            "replicaCount": 1,
            "volumeNamePrefix": "csi"
          }
        }
      ]
    capabilities: "Basic Install"
    categories: "Storage"
    description: CNCF-compliant Kubernetes integration for Infinidat InfiniBox storage systems, offering advanced enterprise functionality for petabyte-scale Kubernetes deployments including Red Hat OpenShift Platform.
    containerImage: registry.connect.redhat.com/infinidat/infinibox-operator-certified:1.1.1
    createdAt: 2020-03-11T10:20:01Z
    support: Infinidat
    certified: "true"
    repository: https://github.com/Infinidat/infinibox-csi-driver
  name: infinibox-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: InfiniboxCsiDriver
      name: infiniboxcsidrivers.charts.helm.k8s.io
      version: v1alpha1
  description: |
    Infinidat InfiniBox Container Storage Interface (CSI) Driver is a CNCF-compliant Kubernetes integration for InfiniBox storage systems, offering advanced enterprise functionality for petabyte-scale Kubernetes deployments including Red Hat OpenShift.
     
    ## Features and Benefits
      
    * **Multi-protocol flexibility** - manage Kubernetes Persistent Volumes attached via block and file protocols, including Fibre Channel, iSCSI, NFS, and NFS TreeQs, with all Kubernetes PV access modes
    * **Multi-petabyte scalability** - support hundreds of thousands of PVs per InfiniBox system and control multiple InfiniBox arrays within a single Kubernetes cluster  
    * **Advanced enterprise features** - manage native InfiniBox snapshots and clones, including restoring from snapshots, and import PVs created outside of InfiniBox CSI Driver
      
    ## Required Parameters
      
    * `hostname` - IP address or hostname of the InfiniBox management interface
    * `username` / `password` - InfiniBox credentials
    * `inbound_user` / `inbound_secret` / `outbound_user` / `outbound_secret` - optional credentials for iSCSI CHAP authentication
    * `SecretName` - secret name, to be used in the StorageClass to define a specific InfiniBox for persistent volumes
  displayName: InfiniBox CSI Driver - Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          verbs:
          - '*'
        - apiGroups:
          - storage.k8s.io
          resources:
          - csidrivers
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - secrets
          - serviceaccounts
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - daemonsets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - infinibox-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - charts.helm.k8s.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: infinibox-operator
      deployments:
      - name: infinibox-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: infinibox-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: infinibox-operator
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: infinibox-operator-certified
                image: registry.connect.redhat.com/infinidat/infinibox-operator-certified:1.1.1
                imagePullPolicy: Always
                name: infinibox-operator
                resources: {}
              serviceAccountName: infinibox-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
    - infinibox
    - storage
    - san
    - nas
    - csi
  maintainers:
    - email: info@infinidat.com
      name: Infinidat
  maturity: alpha
  links:
    - name: Infinidat
      url: https://infinidat.com
    - name: Documentation
      url: https://support.infinidat.com/hc/en-us/articles/360008917097-InfiniBox-CSI-Driver-for-Kubernetes-User-Guide
  provider:
    name: Infinidat
  version: 0.0.1
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAGQAAAATCAIAAADppz96AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAeGVYSWZNTQAqAAAACAAEARIAAwAAAAEAAQAAARoABQAAAAEAAAA+ARsABQAAAAEAAABGh2kABAAAAAEAAABOAAAAAAAAAEgAAAABAAAASAAAAAEAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAZKADAAQAAAABAAAAEwAAAACL10wpAAAACXBIWXMAAAsTAAALEwEAmpwYAAABWWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS40LjAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAgICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyI+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgpMwidZAAAKfklEQVRYw+1YeVSU1xX/VCI6gIhoRIlxiTFNtK02adTYmJ7TnBzT2iSNrakaq+fEpooy7DjDrN8yM4CAIKBxiQ11x6hxQ3ED1KCGuCKr7KsrboCAgP29+zmTYY+e/tlz3uF83rnvvt/93eXdJzeQl/6/elwDeGmwYOL6GcWOy9HQQdKZWkdNR5JYl2D77lLf0JVZoUdNu4NodYGw+7PaG7FhbqvW1yCAL87JKNovhVF0NoqDwSV9yxJXoziQiHBuqwm5Oy/ZS9wQAV5y77Bgrb9V39nOshtt798BwyBewk8KO0jY6Gq3cQCBtD8Cv74Ar9qCbOeU7WibEffO0LrbnS4vIER+cQraprBa6UcmxojmIbzUlySOBP0XkmUYL/U2CLbzIIfOaNHsbPUWe18STGNF8ziJlkiLvqHZxyAM5SVYdrHqw4KnYHpdsjjTt5MVBr5HCCaYcmwL6UWCJCvD81dE86viTwe9IVkmmcNGCyYbSIWdwZGC6TXJ8rJg6ms9CB8evAShbASwx5Ad/BNC6Pezs4Bv13ZkYb+bUeQMAucbyIXohxI78JPTGjilP+QwwREUHA/o0OH8giAZQHuRfVywmvP247yUbdYSby5Ex/aG6JhlgwBNB9lCkBoWgNKVbCpsloNU+AkfL8hm7SD1MgiDZUg+AdxSn59OWbyM/dUaYA06NqdgYbggcSott0TJqbUIjwOdAqaYUN4FhEo/ZtBmyj8Ip/Qnmpw6ktWX6Oc0+hkroi7k5Zu2J3KBqgkmC3Abt2xLz7zK6YywPl6yADoiDzl0zmVlTzKF4ieZi90nT+WUlOaWluWV0aKPgooK3eYtABSxa8+FvLzfh0XAJUQP9r87/X1iahp+gg8gwoU5xiwfSD+z+9RpKMBzQPpgRSQgmXfshGSiOZRbHhKSsOlKQWFOaenTg8rKLhcU4PRplnAuOGS0yDJIrgB8w6AlcWdJVbW4bQe+R1HaIhiRu/eUVFcDcH55eWZh4cX8a/llZbmlpcVV1YfPnuNUGnfqKv07koUyQa1xyzXzY+OfPHnCfPBSTg0NR0jX7j8ICUwMQ5BVGjDIECzzTUxJhZw5r9G/AVr9gytu3GhtbT17Netifj7cO5+Xdz4v/9K1AnXCJm7hP/d+nw79WdGrEOHfmMMQyZziEkiSzpwFX8NQKaKZubHUp+rWreKqKgD4JSKh0sxbxSDtTGOQ3guPQJpvPHQYkquFRWezsn7MzcVCYFpaWmrr6//11TpsActO1Cg4PT9WMFXevAV9mEVckWuoRzBu2rHzalERQMLI/dpaKMBORm4uhOAdIAdR/1J0Rpb4mmTGMXNWxeHUTceOg47JCJRvAJA9rK+/UVNTc//+NEsYwjstdAV+3Xz02KOGhun41hjGgyzfwNLr1xEcbu4CLiCYZTVKUq4UPQ8Pt6ekNre0fBIVw6l16C+QZBUV36ypqW9oOJedjTIBUxMhX+ZbVFGZU1KCD2ZWpf0sJhaQthCkd8MYWesOJiEqM0Dcgi/YKct8cdBbkuVBbW0lGAlWo1cgT1n4l/ogf+89fDjFFNrQ2LQr7SQkiAFaB+hgBYgCn/np6ctX7j54wC1azCTevgh8d2WIzJLJmrsqDhxvOXYCCKYgs7z9EpKPPGpsRIYXVlY2NDbOjFzJelOgavPR4zieyNKPRwr4BpTfuFFQXs7N/pz1MtDE5CwN0X1ZJqamwcO/rARZ2jdBupeyqLIys6Dwr1HROBGFANzOwOQbWFRZhVq2kfX3mFgobD3OIE0nstYfTILEe93XaGTwHO35t4jrl0vX7D8Auc+GjUA4Bumv5182iojoQSTvzFmnLl9pbGp6CTTpjEiuIXRLvEk5npGT+6CuDvoegoRKH9F9g++GrI1Jh5ubW/4QHgnWCysqkB3L1m3gPpuPMrSSZXid9aDlBeUVTY8fw+3s4hLUUfy+/eDUgzC1JwsQl/pcKy9HK0EmfrF6LTaCO/QB7kuv0urr6B12ZMV1StZiVFywGs0ObRR84Vu7eSvkMXv2wv+pALbYO/mHjNv37rHIIftUmrpHj45kZMCRX5tDHenqYNi8lD9k5yAr2RWk5z3pSlU8H1n/PnQYnvwtJpZ54h90Kf8aFD6PjY/fuw/y39nIClgOKpGDZzKvZuTkgLLIXbvRbj1pnugksxhZFdjC7sRg9fvhEfCk+vYdeHKtrDy/rBwKXZN1CBLl+q9xV6D94XTWGfyDzDsSIRe2bWe5rxdQDUCITqRK2BS3b//yhE1ZxcXNzc04C1k/lu5NzA2cl08GyEJm4X7X8+3mhp56VmvrZmoQU5DbSpZZyN4/ofq0BtYFvJRo4Y8fPz556TJ6wYcRK61lGFiGnoXymTWHNazF3rDmQWHH8ALSd6SktVh7lpxZaHCsbL39WFQCVZPQdOrqSqurkXHITRhh9Sv3rNZWOX7vWjMLvH8SGc0tWoL+wvkFsuFm3kJcLCiCt82hrLUv8T7243lwd7PmLrIGUPEXLRKSlAsXcTpoQrPHbIVvXOtQeAayGBHWq2friRSYmEqZ9c3h5JaW1o/gpEoz0RTK0t5LicsVag/r6mdERNl6VuXNm+AL6H9lDkV6Y47tR5POOMqsb9NOYsunbXsWu/W8/dDa5dNf4SU0LKjhIgf7E+g2nEPJvp0gTafbcEMSy6yNh5JRd5bEb7G+OnAQdwK7x1NSWaqG6P4Ru5qVyNHj6A+TTaETBNM7iFBAMC5fyBetWYsL0VOQxlEZns/Nq61/JJfhSJqHuyPLwUAuUTdFHiUkH4UPb7PM8l9/IAlXMssstRYj+2Aa3NFZ9qefqbn/gPUyjA5w1S8INYUrHBkxnMZX+SrBEDiWMmvL8RO4Hz6KigamSXTrZRcX55awDBoFBYPAjGj0cBXjDyNL6c8kau3s6NiGpqb/HGGQpoWtwEFx3+1DkkIIg0ArL1zW3yQfQQG+ihLx8cdseP3OHfQBdAl2HeuMfdjoox3JS0gxdHREF0GS+2l6Zubtu/fY6bgTesws+e0GxFCdFxs/FTTp+cE0p0y2hM1dFT+cCsqNchDJNQxjcXAIPB9NvLDRX8+jH32MBNSzmd72BHtqWc+jrcCyJ9kZRJax/WNwp+ddSJmTZz1C/GeUmF6wh/QOQRpC298yh82PW70gbs2C+Kfrj+gG4MUvyIOeotCBArt8MGeJZliQFwubnn8/PHJh/Br5wSBjwyg+OyYWjduRZo6Or8D2z51+pMfeFpSNA22PGIQlRAdDLta5w4HmvRE08fci+dNT4afG4EoEtbPM7OiYnd7WBxOT4NWiMQy06st8jSL28dNAK6RebSHJ7qHxoULZnSMvKFBzdKcnpKs8RumM8gupL21EQ+hNT1R2rlrrYsXmJiMJ0duiq+g0s5zpaWpbTvRqxf0lT64u1v8DQFnJwbdpKsjbYfRGcbJKEFUP2ujcYSnoie9pZweSoZ3p96dIDLXKu4LkSa8W2wLCF38eGCeC7UH/4WHDhr3D7SQdwbuBLOTLcy8HWn3+1+v5zDp0trFTU89qH8ry2MUhPl0usYvvTnXErnW6N9LuFPFnnNUjqmf9VezWWZGl7QjR/F9oxMt4IGm5TAAAAABJRU5ErkJggg==
    mediatype: "image/png"
